# See https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md
root: true
extends:
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2019
  sourceType: module
plugins:
  - "@typescript-eslint"
  - prettier
rules:
  prettier/prettier:
    - error
