# Docker Compose file for a Baikal server with local mounts instead of Docker volumes

# Before you start docker compose up, make sure that you have prepared
# the local folders to avoid file permission issues with
#
# mkdir -p config Specific/db
# chown -R 101:101 config Specific  <- Use this for Nginx
# chown -R 33:33 config Specific    <- Use this for Apache httpd

version: "2"
services:
  baikal:
    image: ckulka/baikal:nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config:/var/www/baikal/config
      - ./Specific:/var/www/baikal/Specific
