# Docker Compose file for a Baikal server with local mounts instead of Docker volumes

# Before you start docker compose up, make sure that you have prepared
# the local folders to avoid file permission issues with
#
# mkdir -p config Specific/db
# chown -R 101:101 config Specific  <- Use this for Nginx
# chown -R 33:33 config Specific    <- Use this for Apache httpd
#
# If you cannot use the user ids above on your host, re-map the container's
# user ids to the user ids you can use on your host. For more details, see
# https://docs.docker.com/engine/security/userns-remap/.

version: "2"
services:
  baikal:
    image: ckulka/baikal:nginx
    restart: always
    ports:
      - "80:80"
    # Use this flag if you can use the default user ids (see above) and want to
    # ensure correct file permissions every time the container starts.
    # environment:
    #   BAIKAL_ENABLE_CHOWN: "1"
    volumes:
      - ./config:/var/www/baikal/config
      - ./Specific:/var/www/baikal/Specific
