#!/bin/bash

# Use manifest-tool to create the manifest, given the experimental
# "docker manifest" command isn't available yet on Docker Hub.
curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.9.0/manifest-tool-linux-amd64
chmod +x manifest-tool

if [[ $DOCKER_TAG == *nginx ]]
then
  echo "Pushing nginx multi-arch manifest"
  ./manifest-tool push from-spec hooks/manifest-nginx.yaml
else
  echo "Pushing apache multi-arch manifest"
  ./manifest-tool push from-spec hooks/manifest.yaml
  ./manifest-tool push from-spec hooks/manifest-apache.yaml
fi
