# See
# - https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# - https://docs.github.com/en/actions/learn-github-actions/contexts
# - https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
name: Build release images

on:
  release:
    types:
      - published

  workflow_dispatch:

jobs:
  parse_release_tag:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.parse-release-tag.outputs.tag }}
    steps:
      # Get the release version by stripping build metadata from the release name
      - name: Parse release tag
        id: parse-release-tag
        run: echo tag=${GITHUB_REF_NAME/+*/} >> "$GITHUB_OUTPUT"

  apache:
    name: Apache
    needs: parse_release_tag
    uses: ./.github/workflows/build-job.yaml
    with:
      dockerfile: apache.dockerfile
      baikal-version: ${{ github.ref_name }}
      tags: |
        ckulka/baikal:${{ needs.parse_release_tag.outputs.tag }}-apache
        ckulka/baikal:${{ needs.parse_release_tag.outputs.tag }}
        ckulka/baikal:apache
        ckulka/baikal:latest
    secrets: inherit

  apache_php82:
    name: Apache (PHP 8.2)
    needs: parse_release_tag
    uses: ./.github/workflows/build-job.yaml
    with:
      dockerfile: apache-php8.2.dockerfile
      baikal-version: ${{ github.ref_name }}
      tags: |
        ckulka/baikal:${{ needs.parse_release_tag.outputs.tag }}-apache-php8.2
        ckulka/baikal:${{ needs.parse_release_tag.outputs.tag }}-php8.2
        ckulka/baikal:apache-php8.2
    secrets: inherit

  nginx:
    name: Nginx
    needs: parse_release_tag
    uses: ./.github/workflows/build-job.yaml
    with:
      dockerfile: nginx.dockerfile
      baikal-version: ${{ github.ref_name }}
      tags: |
        ckulka/baikal:${{ needs.parse_release_tag.outputs.tag }}-nginx
        ckulka/baikal:nginx
    secrets: inherit

  nginx_php82:
    name: Nginx (PHP 8.2)
    needs: parse_release_tag
    uses: ./.github/workflows/build-job.yaml
    with:
      dockerfile: nginx-php8.2.dockerfile
      baikal-version: ${{ github.ref_name }}
      tags: ckulka/baikal:${{ needs.parse_release_tag.outputs.tag }}-nginx-php8.2
    secrets: inherit
