name: Build job
on:
  workflow_call:
    inputs:
      dockerfile:
        description: Path to the Dockerfile to build
        required: true
        type: string
      tags:
        description: Tags to apply to the image
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        description: DockerHub username
        required: true
      DOCKERHUB_PASSWORD:
        description: DockerHub password
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      # See https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # See https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # See https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # See https://github.com/docker/build-push-action
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: ${{ inputs.dockerfile }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          push: true
          tags: ${{ inputs.tags }}
