name: test

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/docker-test.yml
      - "*.dockerfile"
      - cypress/*
      - cypress.json
      - files/*
      - package.json
      - package-lock.json
  pull_request:
    paths:
      - .github/workflows/docker-test.yml
      - "*.dockerfile"
      - cypress/*
      - cypress.json
      - files/*
      - package.json
      - package-lock.json

jobs:
  test:
    name: Test Docker image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        dockerfile: [apache, apache-php8.0, nginx, nginx-php8.0]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Cypress dependencies
        run: npm ci

      - name: Build and start Baikal
        run: docker run --rm -dp 80:80 $(docker build -qf ${{ matrix.dockerfile }}.dockerfile .)

      - name: Run Cypress tests
        run: npm run test

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results-${{ matrix.dockerfile }}
          path: cypress/videos
