name: Test job

on:
  workflow_call:
    inputs:
      dockerfile:
        description: Path to the Dockerfile
        required: true
        type: string
      ref:
        description: Git reference to test
        default: ${{ github.ref }}
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Get the latest release version from the GitHub API
      - name: Parse release tag
        id: parse-release-tag
        run: |
          echo Parsing tag from latest release ref $REF_NAME
          REF_NAME=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
          echo Latest release ref is $REF_NAME
          BAIKAL_VERSION=${REF_NAME/+*/}
          echo Parsed Baikal version $BAIKAL_VERSION from release $REF_NAME
          echo BAIKAL_VERSION=$BAIKAL_VERSION >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          show-progress: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Install Cypress dependencies
        run: npm ci

      - name: Build Docker image
        id: build
        run: >
          docker build
          --file ${{ inputs.dockerfile }}.dockerfile
          --build-arg VERSION=${{ steps.parse-release-tag.outputs.BAIKAL_VERSION }}
          --tag baikal-image
          .

      - name: Start Baikal container
        run: docker run --rm -dp 80:80 --name ${{ inputs.dockerfile }} baikal-image

      - name: Run Cypress tests
        run: npm run test
        env:
          CYPRESS_BAIKAL_VERSION: ${{ steps.parse-release-tag.outputs.BAIKAL_VERSION }}

      - name: Stop Baikal container
        run: docker stop ${{ inputs.dockerfile }}

      - name: Build and run MailSlurper
        run: |
          docker build -q 'https://github.com/mailslurper/mailslurper.git#release-1.15.0' -t mailslurper
          docker run --rm --detach --name mailslurper -p 8085:8085 -v ${{ github.workspace }}/cypress/fixtures/mailslurper-config.json:/config.json:ro mailslurper

      - name: Start Baikal container with MSMTP configuration
        env:
          MSMTPRC: |
            account default
            host    mailslurper
            port    2500
            from    baikal@example.com
        run: |
          docker run --rm --detach -p 80:80 -e MSMTPRC="$MSMTPRC" --link mailslurper --name baikal baikal-image
          docker cp ${{ github.workspace }}/cypress/fixtures/mail-test.php baikal:/var/www/baikal/html/

      - name: Run Cypress tests incl. MSMTP
        run: npm run test
        env:
          CYPRESS_MSMTP_ENABLED: TRUE
          CYPRESS_BAIKAL_VERSION: ${{ steps.parse-release-tag.outputs.BAIKAL_VERSION }}

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results-${{ inputs.dockerfile }}
          path: cypress/screenshots
